name: Android CI

on:
  push:
    paths-ignore:
      - 'meta/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'meta/**'
    branches: [ master ]

jobs:
  buildAndSign:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      signedFile: ${{ steps.sign_app_bundle.outputs.signedReleaseFile }}
    steps:
      - name: "Set environmental variables"
        run: echo "ORG_GRADLE_PROJECT_VERSION_CODE=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - run: echo ${{github.ref}}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: create the Bundle
        run: ./gradlew bundleProductionRelease "-Pbranch=${GITHUB_REF##*/}" "-Pshortsha=${SHORT_SHA}"
      - name: Sign app Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/productionRelease
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEY_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.1"
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: aab-release.aab
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}

  uploadApp:
    runs-on: ubuntu-latest
    needs: buildAndSign
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: aab-release.aab
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: 'Echo files'
        run: ls ${{steps.download.outputs.download-path}}
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT }}
          packageName: com.saphidev.pharmaciedegarde
          releaseFiles: ${{steps.download.outputs.download-path}}/aab-release.aab
          track: internal

  updateContributorsList:
    needs: uploadApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: commit changes
        run: |
          git config --local user.name "apotox"
          git config --local user.email "apotox@users.noreply.github.com"
          git log
      - name: get-contributors
        run: |
          date +%s > ./meta/contributors.txt
          git shortlog -sn HEAD >> ./meta/contributors.txt
          git commit -am 'update contributors ✌️'
          git push
