name: Android CI

on:
  push:
    paths-ignore:
      - 'meta/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'meta/**'
    branches: [ master ]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: set up JDK 11
  #     uses: actions/setup-java@v2
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'

  #   - name: Grant execute permission for gradlew
  #     run: chmod +x gradlew
  #   - name: Build with Gradle
  #     run: ./gradlew build
  updateContributorsList:
  #  needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: commit changes
        run: |
          git config --local user.name "apotox"
          git config --local user.email "apotox@users.noreply.github.com"
          git log
      - name: get-contributors
        run: |
          date +%s > ./meta/contributors.txt
          git shortlog -sn >> ./meta/contributors.txt
          git commit -am 'update contributors'
          git push
